language: node_js
sudo: false
node_js:
- '6'
- '8'
cache:
  directories:
  - node_modules
install: npm install
script: npm test
deploy:
  provider: npm
  email: hanifbbz@gmail.com
  api_key:
    secure: 2n9mJsm5Wo+ymKALw6L5bH6io5TnKQiFDKNpKPluaSanTA80HZohRb0sD185/3BN9lceQT00rFCI8u0m7E8eq/RlgISAhLnSr1Znu2l39HSqcUZlAKigOMgg82jmzL68UkhXaQcM4bjGwtI3WVKq9Ws2tQLvgCMUvnw7SW+F0PhNaczoepUMVy5k64A2QE9nF3MkDsZK2tyr4FtBjmdkBxbt3x8r7S8CgsBUK60WItMauX1Fi4sNmL+zWuhkqOOh+lEv1jGOKd6GlRCCiate/mT1cnyDymQsz1NAqdpeohPWV1Yhdt+8kPzvNiIlNr3bDuO3KdRP7Kwn+LsBgTcdlL9lixXOu77bn0Eu1yQEwy+GbCEBKbIITXhj/T0xlj/kFbjP8Y+Sa6c0XlzIUCtPokj0kHcIxuipm8EljT915rf7ysyPZE8AhtdLswiwqJEM8ZBlpGl/21F+aPIu3yBsOlYQ4Tf7GOhwtOg5hlcNvXSRjamm5xX4Yvkb4PgCnjGkF3j1nBRsmwKceeIyMaHzGKdL1OT/tTkUSAkc3HSWlnyebyOi+8SSjLWpe7YTanQiCuruqHWIddMQjmfVpSIAEJwJRHUdXZt5UbD2OkOb7dgbyEe8DODaDXirv9mCMmGAJ3sF3nodrUEZLlwD6PamX8yUajmARTVrwcZOtsFExa4=
  on:
    tags: true
    repo: schibsted/identity-sdk
    branch: master
    node: '8'
