language: node_js
sudo: false
node_js:
- '6'
- '8'
cache:
  directories:
  - node_modules
install: npm install
script: npm test
deploy:
  provider: npm
  email: hanifbbz@gmail.com
  api_key:
    secure: HVUAka14u7bq7sHI524z/L+eyLCyy+jZraqNt0qkY+sFfboiKAvn7/XsKv09/UDE65xp/oWJqjUD+ebCwdaGUqOubiGU4U+lhcXTNNfHuIo3LvBrzQZ1Q8n5NzyAcullEJ30tm6poAq1RinP0FInT4/NENWLx4S2/GA+9SHQCJ/4veR54gYmxyqYutAtAQG/v6vbKDtDXgc/UBquq9LkmrIVwNhpg11y914k55W3QEa+xthRsKSJlWAAFVKjO72Er45FPrwSQtU/TAdU8Cfh94Au+eiiksMdkTyyQTakBaUG2z0aaziizDazyI73BHqLbJoyhc/pqvTFbdgjDozwq4rpkSUP48EVLjTQ9t+Js9I7kizi9kaEiQFZmMuhVknr0auu/+ypcA/KT2Tto7klIDzVuOsybFp4nTcD8za9kbW0Iee6nIahdbtecOWRhsGLgoYWL7pS8vwoJeN2lzOuIkDDzMdZJuXbZZXMfVEMhjeG7brMs8XGnme2IbKWYEybI9qE1CSCsU0840wMv6mjTxlbFQQim5cpspGscwxnHO4JaWEMY7zWy4BU8R4M1yxCY7PFokkLUogkZ3dCuTF3QwDsVylun764terw7NFxa8wDLrHQ7/lIkx22QV3T3JRF13kpyFp8SMV4/fgfXliI/B89U3qnCGvNrlcmm+Pvd/A=
  on:
    tags: true
    repo: schibsted/identity-sdk
    branch: master
    # only publish from one row of the build matrix
    node: '8'
